### ISSUE TITLE
In IAM dropdown menu - missing "Lack of MFA" category

### ISSUE THREAD

**Issue by leo100** [iSECPartners/Scout2#25]
Hello,

I've actually need this "Lack of MFA" info (That's the reason I've installed Scout2 ;).
But it seems that this option was removed? Or is there a bug in the latest version of Scout2?

![image](https://cloud.githubusercontent.com/assets/13654798/9079216/2f81a8a8-3b8b-11e5-89f9-ceac6d8a8b39.png)

**Comment by leo100** [comment]
OK,
In the actual AWS console I can see that for my user "IAM->Users": 
Sign-In Credentials: 
Password Yes

But in the Scout report it's set as:
Authentication methods
Password enabled: No

That's probably why "Lack of MFA" doesn't appear.
It mistakenly sets Password enabled: No
In Scout checks......

Can you please have a look?

**Comment by l01cd3v** [comment]
This should be fixed now. I ignore exceptions received when trying to download the loginprofile information because an exception occurs when no login profiles exist and there was a typo in the code.

I also realized that the link to browse to findings was broken after I modified the json structure. This should work as before now.

**Comment by leo100** [comment]
Thanks I01cd3v,

It's fixed now :+1: 
![image](https://cloud.githubusercontent.com/assets/13654798/9080065/9b2dd56a-3b93-11e5-9482-714e8f136bdf.png)

**Comment by l01cd3v** [comment]
Thanks for catching that ! And good luck with these 53 users ;)
