### ISSUE TITLE
This tool is awesome. Is there a way we can get more information about Security Groups?

### ISSUE THREAD

**Issue by gorivishal** [iSECPartners/Scout2#74]
This tool is awesome. Is there a way we can get more information about Security Groups? I am looking for something like the last time the Security Groups were accessed/hit. 

I am willing to work full time on this. Just need to get a kick start and some direction.

**Comment by l01cd3v** [comment]
Hi,

Unfortunately the AWS API does not provide such information (http://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_SecurityGroup.html, http://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_IpPermission.html). In order to get this information, you'll need to use tools such as Security Monkey or the AWS config service.
