### ISSUE TITLE
CSV Credential Parsing

### ISSUE THREAD

**Issue by ahhh** [iSECPartners/Scout2#8]
When creating a CREDENTIALS.CSV and leaving off the (,MFA Serial) field, the script generates the following error: 
```
Traceback (most recent call last):
  File "Scout2.py", line 219, in <module>
    main(args)
  File "Scout2.py", line 39, in main
    key_id, secret, mfa_serial = fetch_creds_from_csv(args.fetch_creds_from_csv[0])
  File "/Scout2/AWSScout2/utils.py", line 208, in fetch_creds_from_csv
    return key_id.rstrip(), secret.rstrip(), mfa_serial
AttributeError: 'NoneType' object has no attribute 'rstrip'
```

Did further testing w/ API credentials downloaded directly from AWS and got the same errors as above.

**Comment by ahhh** [comment]
Fixed by running in zsh not bash on OS X 10.9, and setting credentials as environment variables instead of passing a CSV file. Set env variable like so:

export AWS_ACCESS_KEY_ID=12345
export AWS_SECRET_ACCESS_KEY=abcde

Hope this helps anyone else w/ this issue. Thank you for the cool tool!

**Comment by monikabhadauria** [comment]
@ahhh I am still facing this issue. I am using zsh..still I get this error.

**Comment by l01cd3v** [comment]
Which OS are you using? Did you download the latest version of the code?

**Comment by monikabhadauria** [comment]
@l01cd3v hey I solved the issue by creating new keys. Thanks.

**Comment by byte2binary** [comment]
> 

Worked around issue by running in zsh not bash on OS X 10.9, and setting credentials as environment variables instead of passing a CSV file. Set env variable like so:

export AWS_ACCESS_KEY_ID=12345
export AWS_SECRET_ACCESS_KEY=abcde

Hope this helps anyone else w/ this issue. Thank you for the cool tool!

> 

This worked for me. Somehow setting up PATTH variable removed the error.
